

Running  250411_160001_two-concurrent-sims

mode: result run
doing local
INFO     Loaded mrestimator v0.1.5, writing to /tmp/mre_pevlachos/
INFO     Numba not available, skipping parallelization
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_dwzyfosh.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_r72c9_zm.py Thanks! [brian2]
Traceback (most recent call last):
  File "/home/pevlachos/miniconda3/envs/excinhbal/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pevlachos/miniconda3/envs/excinhbal/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pevlachos/Code/SynapticLifetimes/running/250411_160001_two-concurrent-sims/src/net/xstrct_run.py", line 25, in <module>
    repo = git.Repo('../')
  File "/home/pevlachos/miniconda3/envs/excinhbal/lib/python3.8/site-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/pevlachos/Code/SynapticLifetimes/running
Using 2 cores
Done.
